// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: proto/suggest_request.proto

package suggest_request

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request_Display int32

const (
	Request_Escaped   Request_Display = 0
	Request_Unescaped Request_Display = 1
)

// Enum value maps for Request_Display.
var (
	Request_Display_name = map[int32]string{
		0: "Escaped",
		1: "Unescaped",
	}
	Request_Display_value = map[string]int32{
		"Escaped":   0,
		"Unescaped": 1,
	}
)

func (x Request_Display) Enum() *Request_Display {
	p := new(Request_Display)
	*p = x
	return p
}

func (x Request_Display) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Request_Display) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_suggest_request_proto_enumTypes[0].Descriptor()
}

func (Request_Display) Type() protoreflect.EnumType {
	return &file_proto_suggest_request_proto_enumTypes[0]
}

func (x Request_Display) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Request_Display.Descriptor instead.
func (Request_Display) EnumDescriptor() ([]byte, []int) {
	return file_proto_suggest_request_proto_rawDescGZIP(), []int{0, 0}
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Part         string   `protobuf:"bytes,1,opt,name=part,proto3" json:"part,omitempty"`
	Class        []string `protobuf:"bytes,3,rep,name=class,proto3" json:"class,omitempty"`
	ExcludeClass []string `protobuf:"bytes,4,rep,name=exclude_class,json=excludeClass,proto3" json:"exclude_class,omitempty"`
	Page         int64    `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	Count        int64    `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_suggest_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_suggest_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_suggest_request_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetPart() string {
	if x != nil {
		return x.Part
	}
	return ""
}

func (x *Request) GetClass() []string {
	if x != nil {
		return x.Class
	}
	return nil
}

func (x *Request) GetExcludeClass() []string {
	if x != nil {
		return x.ExcludeClass
	}
	return nil
}

func (x *Request) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Request) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_proto_suggest_request_proto protoreflect.FileDescriptor

var file_proto_suggest_request_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x5f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x73,
	0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xa9,
	0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x72, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x63,
	0x6c, 0x61, 0x73, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x78, 0x63,
	0x6c, 0x75, 0x64, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x25, 0x0a, 0x07, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x12, 0x0b,
	0x0a, 0x07, 0x45, 0x73, 0x63, 0x61, 0x70, 0x65, 0x64, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x55,
	0x6e, 0x65, 0x73, 0x63, 0x61, 0x70, 0x65, 0x64, 0x10, 0x01, 0x42, 0x19, 0x5a, 0x17, 0x73, 0x75,
	0x67, 0x67, 0x65, 0x73, 0x74, 0x2f, 0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x5f, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_suggest_request_proto_rawDescOnce sync.Once
	file_proto_suggest_request_proto_rawDescData = file_proto_suggest_request_proto_rawDesc
)

func file_proto_suggest_request_proto_rawDescGZIP() []byte {
	file_proto_suggest_request_proto_rawDescOnce.Do(func() {
		file_proto_suggest_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_suggest_request_proto_rawDescData)
	})
	return file_proto_suggest_request_proto_rawDescData
}

var file_proto_suggest_request_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_suggest_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_suggest_request_proto_goTypes = []interface{}{
	(Request_Display)(0), // 0: suggest_request.Request.Display
	(*Request)(nil),      // 1: suggest_request.Request
}
var file_proto_suggest_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_suggest_request_proto_init() }
func file_proto_suggest_request_proto_init() {
	if File_proto_suggest_request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_suggest_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_suggest_request_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_suggest_request_proto_goTypes,
		DependencyIndexes: file_proto_suggest_request_proto_depIdxs,
		EnumInfos:         file_proto_suggest_request_proto_enumTypes,
		MessageInfos:      file_proto_suggest_request_proto_msgTypes,
	}.Build()
	File_proto_suggest_request_proto = out.File
	file_proto_suggest_request_proto_rawDesc = nil
	file_proto_suggest_request_proto_goTypes = nil
	file_proto_suggest_request_proto_depIdxs = nil
}
