// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: proto/suggest_trie.proto

package suggest_trie

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Weight       float32          `protobuf:"fixed32,1,opt,name=Weight,proto3" json:"Weight,omitempty"`
	OriginalText string           `protobuf:"bytes,2,opt,name=OriginalText,proto3" json:"OriginalText,omitempty"`
	Data         *structpb.Struct `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_suggest_trie_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_suggest_trie_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_suggest_trie_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Item) GetOriginalText() string {
	if x != nil {
		return x.OriginalText
	}
	return ""
}

func (x *Item) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type ClassItems struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Class       string    `protobuf:"bytes,1,opt,name=Class,proto3" json:"Class,omitempty"`
	AntiClass   string    `protobuf:"bytes,2,opt,name=AntiClass,proto3" json:"AntiClass,omitempty"`
	ItemWeights []float32 `protobuf:"fixed32,3,rep,packed,name=ItemWeights,proto3" json:"ItemWeights,omitempty"`
	ItemIndexes []uint32  `protobuf:"varint,4,rep,packed,name=ItemIndexes,proto3" json:"ItemIndexes,omitempty"`
}

func (x *ClassItems) Reset() {
	*x = ClassItems{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_suggest_trie_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassItems) ProtoMessage() {}

func (x *ClassItems) ProtoReflect() protoreflect.Message {
	mi := &file_proto_suggest_trie_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassItems.ProtoReflect.Descriptor instead.
func (*ClassItems) Descriptor() ([]byte, []int) {
	return file_proto_suggest_trie_proto_rawDescGZIP(), []int{1}
}

func (x *ClassItems) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *ClassItems) GetAntiClass() string {
	if x != nil {
		return x.AntiClass
	}
	return ""
}

func (x *ClassItems) GetItemWeights() []float32 {
	if x != nil {
		return x.ItemWeights
	}
	return nil
}

func (x *ClassItems) GetItemIndexes() []uint32 {
	if x != nil {
		return x.ItemIndexes
	}
	return nil
}

type SuggestTrie struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DescendantKeys  []uint32       `protobuf:"varint,1,rep,packed,name=DescendantKeys,proto3" json:"DescendantKeys,omitempty"`
	DescendantTries []*SuggestTrie `protobuf:"bytes,2,rep,name=DescendantTries,proto3" json:"DescendantTries,omitempty"`
	Items           []*ClassItems  `protobuf:"bytes,4,rep,name=Items,proto3" json:"Items,omitempty"`
}

func (x *SuggestTrie) Reset() {
	*x = SuggestTrie{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_suggest_trie_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuggestTrie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestTrie) ProtoMessage() {}

func (x *SuggestTrie) ProtoReflect() protoreflect.Message {
	mi := &file_proto_suggest_trie_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestTrie.ProtoReflect.Descriptor instead.
func (*SuggestTrie) Descriptor() ([]byte, []int) {
	return file_proto_suggest_trie_proto_rawDescGZIP(), []int{2}
}

func (x *SuggestTrie) GetDescendantKeys() []uint32 {
	if x != nil {
		return x.DescendantKeys
	}
	return nil
}

func (x *SuggestTrie) GetDescendantTries() []*SuggestTrie {
	if x != nil {
		return x.DescendantTries
	}
	return nil
}

func (x *SuggestTrie) GetItems() []*ClassItems {
	if x != nil {
		return x.Items
	}
	return nil
}

type SuggestData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trie  *SuggestTrie `protobuf:"bytes,1,opt,name=Trie,proto3" json:"Trie,omitempty"`
	Items []*Item      `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
}

func (x *SuggestData) Reset() {
	*x = SuggestData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_suggest_trie_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuggestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestData) ProtoMessage() {}

func (x *SuggestData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_suggest_trie_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestData.ProtoReflect.Descriptor instead.
func (*SuggestData) Descriptor() ([]byte, []int) {
	return file_proto_suggest_trie_proto_rawDescGZIP(), []int{3}
}

func (x *SuggestData) GetTrie() *SuggestTrie {
	if x != nil {
		return x.Trie
	}
	return nil
}

func (x *SuggestData) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_suggest_trie_proto protoreflect.FileDescriptor

var file_proto_suggest_trie_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x5f,
	0x74, 0x72, 0x69, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x75, 0x67, 0x67,
	0x65, 0x73, 0x74, 0x5f, 0x74, 0x72, 0x69, 0x65, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6f, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16,
	0x0a, 0x06, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06,
	0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x61, 0x6c, 0x54, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x4f, 0x72,
	0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x54, 0x65, 0x78, 0x74, 0x12, 0x2b, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x84, 0x01, 0x0a, 0x0a, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09,
	0x41, 0x6e, 0x74, 0x69, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x41, 0x6e, 0x74, 0x69, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x49, 0x74,
	0x65, 0x6d, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x02, 0x52,
	0x0b, 0x49, 0x74, 0x65, 0x6d, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x12, 0x20, 0x0a, 0x0b,
	0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0d, 0x52, 0x0b, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x22, 0xaa,
	0x01, 0x0a, 0x0b, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x54, 0x72, 0x69, 0x65, 0x12, 0x26,
	0x0a, 0x0e, 0x44, 0x65, 0x73, 0x63, 0x65, 0x6e, 0x64, 0x61, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0e, 0x44, 0x65, 0x73, 0x63, 0x65, 0x6e, 0x64, 0x61,
	0x6e, 0x74, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x43, 0x0a, 0x0f, 0x44, 0x65, 0x73, 0x63, 0x65, 0x6e,
	0x64, 0x61, 0x6e, 0x74, 0x54, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x72, 0x69, 0x65, 0x2e, 0x53,
	0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x54, 0x72, 0x69, 0x65, 0x52, 0x0f, 0x44, 0x65, 0x73, 0x63,
	0x65, 0x6e, 0x64, 0x61, 0x6e, 0x74, 0x54, 0x72, 0x69, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x05, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x75, 0x67,
	0x67, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x72, 0x69, 0x65, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x52, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x66, 0x0a, 0x0b, 0x53,
	0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2d, 0x0a, 0x04, 0x54, 0x72,
	0x69, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x75, 0x67, 0x67, 0x65,
	0x73, 0x74, 0x5f, 0x74, 0x72, 0x69, 0x65, 0x2e, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x54,
	0x72, 0x69, 0x65, 0x52, 0x04, 0x54, 0x72, 0x69, 0x65, 0x12, 0x28, 0x0a, 0x05, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x75, 0x67, 0x67, 0x65,
	0x73, 0x74, 0x5f, 0x74, 0x72, 0x69, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x49, 0x74,
	0x65, 0x6d, 0x73, 0x42, 0x16, 0x5a, 0x14, 0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x2f, 0x73,
	0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x72, 0x69, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_suggest_trie_proto_rawDescOnce sync.Once
	file_proto_suggest_trie_proto_rawDescData = file_proto_suggest_trie_proto_rawDesc
)

func file_proto_suggest_trie_proto_rawDescGZIP() []byte {
	file_proto_suggest_trie_proto_rawDescOnce.Do(func() {
		file_proto_suggest_trie_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_suggest_trie_proto_rawDescData)
	})
	return file_proto_suggest_trie_proto_rawDescData
}

var file_proto_suggest_trie_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_suggest_trie_proto_goTypes = []interface{}{
	(*Item)(nil),            // 0: suggest_trie.Item
	(*ClassItems)(nil),      // 1: suggest_trie.ClassItems
	(*SuggestTrie)(nil),     // 2: suggest_trie.SuggestTrie
	(*SuggestData)(nil),     // 3: suggest_trie.SuggestData
	(*structpb.Struct)(nil), // 4: google.protobuf.Struct
}
var file_proto_suggest_trie_proto_depIdxs = []int32{
	4, // 0: suggest_trie.Item.Data:type_name -> google.protobuf.Struct
	2, // 1: suggest_trie.SuggestTrie.DescendantTries:type_name -> suggest_trie.SuggestTrie
	1, // 2: suggest_trie.SuggestTrie.Items:type_name -> suggest_trie.ClassItems
	2, // 3: suggest_trie.SuggestData.Trie:type_name -> suggest_trie.SuggestTrie
	0, // 4: suggest_trie.SuggestData.Items:type_name -> suggest_trie.Item
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_suggest_trie_proto_init() }
func file_proto_suggest_trie_proto_init() {
	if File_proto_suggest_trie_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_suggest_trie_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_suggest_trie_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassItems); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_suggest_trie_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuggestTrie); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_suggest_trie_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuggestData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_suggest_trie_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_suggest_trie_proto_goTypes,
		DependencyIndexes: file_proto_suggest_trie_proto_depIdxs,
		MessageInfos:      file_proto_suggest_trie_proto_msgTypes,
	}.Build()
	File_proto_suggest_trie_proto = out.File
	file_proto_suggest_trie_proto_rawDesc = nil
	file_proto_suggest_trie_proto_goTypes = nil
	file_proto_suggest_trie_proto_depIdxs = nil
}
