// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: proto/suggest_trie.proto

package suggest_trie

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Weight         float32          `protobuf:"fixed32,1,opt,name=Weight,proto3" json:"Weight,omitempty"`
	OriginalText   string           `protobuf:"bytes,2,opt,name=OriginalText,proto3" json:"OriginalText,omitempty"`
	NormalizedText string           `protobuf:"bytes,3,opt,name=NormalizedText,proto3" json:"NormalizedText,omitempty"`
	Data           *structpb.Struct `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_suggest_trie_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_suggest_trie_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_suggest_trie_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Item) GetOriginalText() string {
	if x != nil {
		return x.OriginalText
	}
	return ""
}

func (x *Item) GetNormalizedText() string {
	if x != nil {
		return x.NormalizedText
	}
	return ""
}

func (x *Item) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type SuggestTrieItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Weight          float32 `protobuf:"fixed32,1,opt,name=Weight,proto3" json:"Weight,omitempty"`
	OriginalItemIdx uint32  `protobuf:"varint,2,opt,name=OriginalItemIdx,proto3" json:"OriginalItemIdx,omitempty"`
}

func (x *SuggestTrieItem) Reset() {
	*x = SuggestTrieItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_suggest_trie_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuggestTrieItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestTrieItem) ProtoMessage() {}

func (x *SuggestTrieItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_suggest_trie_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestTrieItem.ProtoReflect.Descriptor instead.
func (*SuggestTrieItem) Descriptor() ([]byte, []int) {
	return file_proto_suggest_trie_proto_rawDescGZIP(), []int{1}
}

func (x *SuggestTrieItem) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *SuggestTrieItem) GetOriginalItemIdx() uint32 {
	if x != nil {
		return x.OriginalItemIdx
	}
	return 0
}

type Descendant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  uint32       `protobuf:"varint,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Trie *SuggestTrie `protobuf:"bytes,2,opt,name=Trie,proto3" json:"Trie,omitempty"`
}

func (x *Descendant) Reset() {
	*x = Descendant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_suggest_trie_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Descendant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Descendant) ProtoMessage() {}

func (x *Descendant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_suggest_trie_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Descendant.ProtoReflect.Descriptor instead.
func (*Descendant) Descriptor() ([]byte, []int) {
	return file_proto_suggest_trie_proto_rawDescGZIP(), []int{2}
}

func (x *Descendant) GetKey() uint32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *Descendant) GetTrie() *SuggestTrie {
	if x != nil {
		return x.Trie
	}
	return nil
}

type SuggestTrie struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Descendants []*Descendant      `protobuf:"bytes,1,rep,name=Descendants,proto3" json:"Descendants,omitempty"`
	Items       []*SuggestTrieItem `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
}

func (x *SuggestTrie) Reset() {
	*x = SuggestTrie{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_suggest_trie_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuggestTrie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestTrie) ProtoMessage() {}

func (x *SuggestTrie) ProtoReflect() protoreflect.Message {
	mi := &file_proto_suggest_trie_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestTrie.ProtoReflect.Descriptor instead.
func (*SuggestTrie) Descriptor() ([]byte, []int) {
	return file_proto_suggest_trie_proto_rawDescGZIP(), []int{3}
}

func (x *SuggestTrie) GetDescendants() []*Descendant {
	if x != nil {
		return x.Descendants
	}
	return nil
}

func (x *SuggestTrie) GetItems() []*SuggestTrieItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type SuggestData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trie  *SuggestTrie `protobuf:"bytes,1,opt,name=Trie,proto3" json:"Trie,omitempty"`
	Items []*Item      `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
}

func (x *SuggestData) Reset() {
	*x = SuggestData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_suggest_trie_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuggestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestData) ProtoMessage() {}

func (x *SuggestData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_suggest_trie_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestData.ProtoReflect.Descriptor instead.
func (*SuggestData) Descriptor() ([]byte, []int) {
	return file_proto_suggest_trie_proto_rawDescGZIP(), []int{4}
}

func (x *SuggestData) GetTrie() *SuggestTrie {
	if x != nil {
		return x.Trie
	}
	return nil
}

func (x *SuggestData) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_suggest_trie_proto protoreflect.FileDescriptor

var file_proto_suggest_trie_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x5f,
	0x74, 0x72, 0x69, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x75, 0x67, 0x67,
	0x65, 0x73, 0x74, 0x5f, 0x74, 0x72, 0x69, 0x65, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x97, 0x01, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x16, 0x0a, 0x06, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x06, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x4f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x61, 0x6c, 0x54, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x4f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x54, 0x65, 0x78, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x4e,
	0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x54, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x54,
	0x65, 0x78, 0x74, 0x12, 0x2b, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x22, 0x53, 0x0a, 0x0f, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x54, 0x72, 0x69, 0x65, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x06, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x4f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x78, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x49, 0x74,
	0x65, 0x6d, 0x49, 0x64, 0x78, 0x22, 0x4d, 0x0a, 0x0a, 0x44, 0x65, 0x73, 0x63, 0x65, 0x6e, 0x64,
	0x61, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x2d, 0x0a, 0x04, 0x54, 0x72, 0x69, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x72,
	0x69, 0x65, 0x2e, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x54, 0x72, 0x69, 0x65, 0x52, 0x04,
	0x54, 0x72, 0x69, 0x65, 0x22, 0x7e, 0x0a, 0x0b, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x54,
	0x72, 0x69, 0x65, 0x12, 0x3a, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x65, 0x6e, 0x64, 0x61, 0x6e,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x75, 0x67, 0x67, 0x65,
	0x73, 0x74, 0x5f, 0x74, 0x72, 0x69, 0x65, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x65, 0x6e, 0x64, 0x61,
	0x6e, 0x74, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x65, 0x6e, 0x64, 0x61, 0x6e, 0x74, 0x73, 0x12,
	0x33, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x72, 0x69, 0x65, 0x2e, 0x53, 0x75,
	0x67, 0x67, 0x65, 0x73, 0x74, 0x54, 0x72, 0x69, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x22, 0x66, 0x0a, 0x0b, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x2d, 0x0a, 0x04, 0x54, 0x72, 0x69, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x72, 0x69, 0x65,
	0x2e, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x54, 0x72, 0x69, 0x65, 0x52, 0x04, 0x54, 0x72,
	0x69, 0x65, 0x12, 0x28, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x72, 0x69, 0x65,
	0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x42, 0x16, 0x5a, 0x14,
	0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x2f, 0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x5f,
	0x74, 0x72, 0x69, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_suggest_trie_proto_rawDescOnce sync.Once
	file_proto_suggest_trie_proto_rawDescData = file_proto_suggest_trie_proto_rawDesc
)

func file_proto_suggest_trie_proto_rawDescGZIP() []byte {
	file_proto_suggest_trie_proto_rawDescOnce.Do(func() {
		file_proto_suggest_trie_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_suggest_trie_proto_rawDescData)
	})
	return file_proto_suggest_trie_proto_rawDescData
}

var file_proto_suggest_trie_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_suggest_trie_proto_goTypes = []interface{}{
	(*Item)(nil),            // 0: suggest_trie.Item
	(*SuggestTrieItem)(nil), // 1: suggest_trie.SuggestTrieItem
	(*Descendant)(nil),      // 2: suggest_trie.Descendant
	(*SuggestTrie)(nil),     // 3: suggest_trie.SuggestTrie
	(*SuggestData)(nil),     // 4: suggest_trie.SuggestData
	(*structpb.Struct)(nil), // 5: google.protobuf.Struct
}
var file_proto_suggest_trie_proto_depIdxs = []int32{
	5, // 0: suggest_trie.Item.Data:type_name -> google.protobuf.Struct
	3, // 1: suggest_trie.Descendant.Trie:type_name -> suggest_trie.SuggestTrie
	2, // 2: suggest_trie.SuggestTrie.Descendants:type_name -> suggest_trie.Descendant
	1, // 3: suggest_trie.SuggestTrie.Items:type_name -> suggest_trie.SuggestTrieItem
	3, // 4: suggest_trie.SuggestData.Trie:type_name -> suggest_trie.SuggestTrie
	0, // 5: suggest_trie.SuggestData.Items:type_name -> suggest_trie.Item
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_suggest_trie_proto_init() }
func file_proto_suggest_trie_proto_init() {
	if File_proto_suggest_trie_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_suggest_trie_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_suggest_trie_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuggestTrieItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_suggest_trie_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Descendant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_suggest_trie_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuggestTrie); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_suggest_trie_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuggestData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_suggest_trie_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_suggest_trie_proto_goTypes,
		DependencyIndexes: file_proto_suggest_trie_proto_depIdxs,
		MessageInfos:      file_proto_suggest_trie_proto_msgTypes,
	}.Build()
	File_proto_suggest_trie_proto = out.File
	file_proto_suggest_trie_proto_rawDesc = nil
	file_proto_suggest_trie_proto_goTypes = nil
	file_proto_suggest_trie_proto_depIdxs = nil
}
